In [2]:
#Data Creation, Cleaning and Loading into CSV using Pandas

In [3]:
! pip install faker

Collecting faker
  Downloading faker-40.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from faker) (2025.3)
Downloading faker-40.1.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 26.1 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.1.0

In [4]:
from faker import Faker
import pandas as pd
import numpy as np
import random

fake = Faker("ar_EG")
random.seed(42)
np.random.seed(42)

N = 6000
years = list(range(2015, 2025))

regions = [
    ("Cairo", 0.22, 0.95),
    ("Giza", 0.18, 0.90),
    ("Alexandria", 0.12, 0.92),
    ("Delta", 0.28, 0.60),
    ("Upper Egypt", 0.20, 0.40)
]

tariffs = {
    "WE": {
        "Fixed Broadband": [
            ("WE Start", 140, 10),
            ("WE Bronze", 250, 30),
            ("WE Silver", 400, 50),
            ("WE Gold", 700, 100)
        ],
        "Mobile Data": [
            ("WE Mobile 20GB", 120, 10),
            ("WE Mobile 40GB", 200, 20),
            ("WE Mobile 80GB", 350, 30)
        ]
    },
    "Vodafone": {
        "Fixed Broadband": [
            ("Vodafone Basic", 200, 30),
            ("Vodafone Plus", 350, 50),
            ("Vodafone Max", 650, 100)
        ],
        "Mobile Data": [
            ("Vodafone Red 20GB", 150, 15),
            ("Vodafone Red 40GB", 260, 25),
            ("Vodafone Red 80GB", 450, 40)
        ]
    },
    "Orange": {
        "Fixed Broadband": [
            ("Orange Home", 180, 30),
            ("Orange Extra", 330, 50),
            ("Orange Ultra", 600, 100)
        ],
        "Mobile Data": [
            ("Orange Go 20GB", 140, 15),
            ("Orange Go 40GB", 240, 25),
            ("Orange Go 80GB", 420, 40)
        ]
    },
    "Etisalat": {
        "Fixed Broadband": [
            ("Etisalat Home", 190, 30),
            ("Etisalat Power", 340, 50),
            ("Etisalat Extreme", 620, 100)
        ],
        "Mobile Data": [
            ("Etisalat Mix 20GB", 130, 15),
            ("Etisalat Mix 40GB", 230, 25),
            ("Etisalat Mix 80GB", 410, 40)
        ]
    }
}

data = []

for i in range(1, N + 1):

    age_group = np.random.choice(
        ["15-24", "25-34", "35-44", "45-54", "55+"],
        p=[0.22, 0.24, 0.20, 0.18, 0.16]
    )

    if age_group == "15-24":
        age = random.randint(15, 24)
        base_hours = random.uniform(4.5, 7.5)
        purpose = np.random.choice(["Social Media", "Streaming", "Gaming"], p=[0.45, 0.35, 0.20])
    elif age_group == "25-34":
        age = random.randint(25, 34)
        base_hours = random.uniform(4, 6.5)
        purpose = np.random.choice(["Work", "Streaming", "Social Media"], p=[0.40, 0.35, 0.25])
    elif age_group == "35-44":
        age = random.randint(35, 44)
        base_hours = random.uniform(3, 5.5)
        purpose = np.random.choice(["Work", "News", "Streaming"], p=[0.45, 0.30, 0.25])
    elif age_group == "45-54":
        age = random.randint(45, 54)
        base_hours = random.uniform(2.5, 4.5)
        purpose = np.random.choice(["News", "Communication"], p=[0.6, 0.4])
    else:
        age = random.randint(55, 75)
        base_hours = random.uniform(1.5, 3)
        purpose = np.random.choice(["News", "Communication"], p=[0.7, 0.3])

    region_name, _, urban = random.choices(regions, weights= [weg[1] for weg in regions])[0]

    is_internet_user = np.random.choice([1, 0], p=[0.83, 0.17])

    isp = np.random.choice(["WE", "Vodafone", "Orange", "Etisalat"],
                           p=[0.46, 0.22, 0.17, 0.15])

    connection = np.random.choice(["Mobile Data", "Fixed Broadband"], p=[0.72, 0.28])

    if is_internet_user:
        tariff_name, cost, speed = random.choice(tariffs[isp][connection])
        hours = base_hours + (speed / 100) * random.uniform(0.5, 1.2)
    else:
        tariff_name, cost, speed, hours, purpose = "None", 0, 0, 0, "None"

    data.append([
        i, i, age, random.choice(["Male", "Female"]),
        region_name, urban, is_internet_user,
        isp, connection, tariff_name,
        round(hours, 1), purpose,
        cost, speed, random.choice(years)
    ])

columns = [
    "record_id", "user_id", "age", "gender",
    "region_name", "urban_level", "is_internet_user",
    "isp", "connection_type", "tariff_name",
    "daily_hours", "usage_purpose",
    "monthly_cost_egp", "download_speed_mbps", "year"
]

df = pd.DataFrame(data, columns=columns)
df.to_csv("egypt_internet_usage.csv", index=False)

In [5]:
df

,record_id,user_id,age,gender,region_name,urban_level,is_internet_user,isp,connection_type,tariff_name,daily_hours,usage_purpose,monthly_cost_egp,download_speed_mbps,year
0,1,1,26,Male,Giza,0.90,1,Vodafone,Mobile Data,Vodafone Red 20GB,4.2,Social Media,150,15,2023
1,2,2,16,Male,Cairo,0.95,0,Vodafone,Mobile Data,None,0.0,None,0,0,2018
2,3,3,18,Male,Cairo,0.95,0,WE,Mobile Data,None,0.0,None,0,0,2023
3,4,4,21,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 20GB,5.3,Social Media,120,10,2021
4,5,5,40,Female,Cairo,0.95,1,WE,Mobile Data,WE Mobile 40GB,3.8,Work,200,20,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5996,5996,26,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 40GB,4.9,Work,200,20,2021
5996,5997,5997,26,Female,Cairo,0.95,0,Orange,Mobile Data,None,0.0,None,0,0,2018
5997,5998,5998,36,Female,Cairo,0.95,1,Vodafone,Mobile Data,Vodafone Red 80GB,5.4,News,450,40,2021
5998,5999,5999,42,Female,Upper Egypt,0.40,1,WE,Mobile Data,WE Mobile 40GB,4.3,Streaming,200,20,2018
5999,6000,6000,75,Female,Cairo,0.95,1,WE,Mobile Data,WE Mobile 80GB,1.9,Communication,350,30,2024

In [6]:
df.isnull().sum()

record_id              0
user_id                0
age                    0
gender                 0
region_name            0
urban_level            0
is_internet_user       0
isp                    0
connection_type        0
tariff_name            0
daily_hours            0
usage_purpose          0
monthly_cost_egp       0
download_speed_mbps    0
year                   0
dtype: int64

In [7]:
df['Reason_Not_Using_Internet'] = None

In [8]:
df.loc[df["usage_purpose"] == "None", "Reason_Not_Using_Internet"] = np.random.choice(
    [
    "Cannot afford device",
    "No internet coverage",
    "Low digital literacy",
    "No perceived need",
    "Physical disability"
],
size= (df['usage_purpose'] == "None").sum(),
p=[0.30, 0.25, 0.20, 0.15, 0.10]
)

In [9]:
df['Age_Group'] = None

In [10]:
def Assign_Age_Group(age):
    if 15 <= age <= 24:
        return "15-24"
    elif 25 <= age <= 34:
        return "25-34"
    elif 35 <= age <= 44:
        return "35-44"
    elif 45 <= age <= 54:
        return "45-54"
    else:
      return "55+"

df['Age_Group'] = df['age'].apply(Assign_Age_Group)

In [11]:
df['Reason_Not_Using_Internet'] = df['Reason_Not_Using_Internet'].replace(np.nan , "IS_Internet_User")

In [12]:
df.to_csv("egypt_internet_usage.csv", index=False)

In [13]:
df['Reason_Not_Using_Internet'].unique()

array(['IS_Internet_User', 'Low digital literacy', 'No internet coverage',
       'Physical disability', 'Cannot afford device', 'No perceived need'],
      dtype=object)

In [14]:
df.loc[df['is_internet_user'] == 0, 'connection_type'] = 'None'

In [20]:
df.tail(40)

,record_id,user_id,age,gender,region_name,urban_level,is_internet_user,isp,connection_type,tariff_name,daily_hours,usage_purpose,monthly_cost_egp,download_speed_mbps,year,Reason_Not_Using_Internet,Age_Group
5960,5961,5961,54,Male,Giza,0.90,1,WE,Mobile Data,WE Mobile 80GB,3.9,News,350,30,2021,IS_Internet_User,45-54
5961,5962,5962,62,Female,Cairo,0.95,1,Etisalat,Mobile Data,Etisalat Mix 20GB,2.1,Communication,130,15,2022,IS_Internet_User,55+
5962,5963,5963,33,Male,Alexandria,0.92,0,No is Sim Owner,None,None,0.0,None,0,0,2017,Cannot afford device,25-34
5963,5964,5964,51,Male,Alexandria,0.92,1,WE,Mobile Data,WE Mobile 20GB,3.2,News,120,10,2023,IS_Internet_User,45-54
5964,5965,5965,59,Female,Delta,0.60,1,WE,Mobile Data,WE Mobile 20GB,2.8,News,120,10,2023,IS_Internet_User,55+
5965,5966,5966,34,Male,Delta,0.60,1,Orange,Mobile Data,Orange Go 40GB,5.9,Streaming,240,25,2019,IS_Internet_User,25-34
5966,5967,5967,34,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 80GB,6.7,Social Media,350,30,2023,IS_Internet_User,25-34
5967,5968,5968,29,Female,Delta,0.60,1,Etisalat,Fixed Broadband,Etisalat Extreme,5.4,Work,620,100,2020,IS_Internet_User,25-34
5968,5969,5969,48,Male,Giza,0.90,1,WE,Mobile Data,WE Mobile 80GB,3.7,News,350,30,2022,IS_Internet_User,45-54
5969,5970,5970,31,Female,Delta,0.60,1,WE,Mobile Data,WE Mobile 40GB,4.7,Streaming,200,20,2015,IS_Internet_User,25-34
5970,5971,5971,32,Female,Alexandria,0.92,1,WE,Mobile Data,WE Mobile 80GB,6.4,Work,350,30,2023,IS_Internet_User,25-34
5971,5972,5972,16,Female,Giza,0.90,1,Orange,Mobile Data,Orange Go 20GB,5.4,Social Media,140,15,2015,IS_Internet_User,15-24
5972,5973,5973,32,Male,Cairo,0.95,1,WE,Fixed Broadband,WE Bronze,5.2,Work,250,30,2015,IS_Internet_User,25-34
5973,5974,5974,51,Female,Delta,0.60,1,WE,Mobile Data,WE Mobile 40GB,3.3,News,200,20,2017,IS_Internet_User,45-54
5974,5975,5975,54,Female,Delta,0.60,1,Vodafone,Mobile Data,Vodafone Red 20GB,3.5,News,150,15,2019,IS_Internet_User,45-54
5975,5976,5976,59,Female,Cairo,0.95,1,WE,Mobile Data,WE Mobile 40GB,2.3,Communication,200,20,2024,IS_Internet_User,55+
5976,5977,5977,54,Female,Upper Egypt,0.40,1,Etisalat,Mobile Data,Etisalat Mix 20GB,3.0,Communication,130,15,2018,IS_Internet_User,45-54
5977,5978,5978,31,Female,Upper Egypt,0.40,1,Orange,Mobile Data,Orange Go 40GB,5.3,Work,240,25,2020,IS_Internet_User,25-34
5978,5979,5979,71,Male,Alexandria,0.92,1,Orange,Mobile Data,Orange Go 80GB,3.2,News,420,40,2022,IS_Internet_User,55+
5979,5980,5980,46,Male,Upper Egypt,0.40,1,Vodafone,Fixed Broadband,Vodafone Plus,4.6,News,350,50,2020,IS_Internet_User,45-54
5980,5981,5981,44,Female,Alexandria,0.92,1,WE,Fixed Broadband,WE Gold,4.0,News,700,100,2018,IS_Internet_User,35-44
5981,5982,5982,31,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 40GB,4.1,Work,200,20,2015,IS_Internet_User,25-34
5982,5983,5983,29,Male,Upper Egypt,0.40,1,Vodafone,Mobile Data,Vodafone Red 40GB,4.3,Work,260,25,2015,IS_Internet_User,25-34
5983,5984,5984,29,Female,Upper Egypt,0.40,1,Vodafone,Mobile Data,Vodafone Red 40GB,4.5,Social Media,260,25,2022,IS_Internet_User,25-34
5984,5985,5985,40,Male,Delta,0.60,1,Etisalat,Fixed Broadband,Etisalat Home,3.6,Work,190,30,2022,IS_Internet_User,35-44
5985,5986,5986,24,Female,Delta,0.60,0,WE,None,None,0.0,None,0,0,2016,No internet coverage,15-24
5986,5987,5987,32,Female,Delta,0.60,0,Vodafone,None,None,0.0,None,0,0,2015,Low digital literacy,25-34
5987,5988,5988,31,Male,Delta,0.60,0,No is Sim Owner,None,None,0.0,None,0,0,2022,Cannot afford device,25-34
5988,5989,5989,47,Male,Delta,0.60,0,Orange,None,None,0.0,None,0,0,2019,No internet coverage,45-54
5989,5990,5990,18,Female,Delta,0.60,1,Etisalat,Mobile Data,Etisalat Mix 40GB,6.3,Social Media,230,25,2022,IS_Internet_User,15-24
5990,5991,5991,21,Female,Upper Egypt,0.40,1,Orange,Fixed Broadband,Orange Extra,5.2,Social Media,330,50,2019,IS_Internet_User,15-24
5991,5992,5992,48,Male,Giza,0.90,0,No is Sim Owner,None,None,0.0,None,0,0,2024,Physical disability,45-54
5992,5993,5993,16,Female,Giza,0.90,1,Vodafone,Mobile Data,Vodafone Red 40GB,5.6,Social Media,260,25,2017,IS_Internet_User,15-24
5993,5994,5994,20,Female,Upper Egypt,0.40,0,No is Sim Owner,None,None,0.0,None,0,0,2022,Cannot afford device,15-24
5994,5995,5995,33,Male,Delta,0.60,1,Etisalat,Mobile Data,Etisalat Mix 80GB,4.7,Social Media,410,40,2021,IS_Internet_User,25-34
5995,5996,5996,26,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 40GB,4.9,Work,200,20,2021,IS_Internet_User,25-34
5996,5997,5997,26,Female,Cairo,0.95,0,No is Sim Owner,None,None,0.0,None,0,0,2018,Cannot afford device,25-34
5997,5998,5998,36,Female,Cairo,0.95,1,Vodafone,Mobile Data,Vodafone Red 80GB,5.4,News,450,40,2021,IS_Internet_User,35-44
5998,5999,5999,42,Female,Upper Egypt,0.40,1,WE,Mobile Data,WE Mobile 40GB,4.3,Streaming,200,20,2018,IS_Internet_User,35-44
5999,6000,6000,75,Female,Cairo,0.95,1,WE,Mobile Data,WE Mobile 80GB,1.9,Communication,350,30,2024,IS_Internet_User,55+

In [21]:
df.loc[(df['Reason_Not_Using_Internet'] == "Cannot afford device") | (df['Reason_Not_Using_Internet'] == 'Physical disability' ), 'isp'] = 'No is Sim Owner'

In [22]:
# perform analysis using pandas

In [30]:
# Get Data
import pandas as pd
import numpy as np

df_Data = pd.read_csv("/content/egypt_internet_usage.csv")
df_Data.head()

,record_id,user_id,age,gender,region_name,urban_level,is_internet_user,isp,connection_type,tariff_name,daily_hours,usage_purpose,monthly_cost_egp,download_speed_mbps,year,Reason_Not_Using_Internet,Age_Group
0,1,1,26,Male,Giza,0.90,1,Vodafone,Mobile Data,Vodafone Red 20GB,4.2,Social Media,150,15,2023,IS_Internet_User,25-34
1,2,2,16,Male,Cairo,0.95,0,Vodafone,Mobile Data,NaN,0.0,NaN,0,0,2018,Low digital literacy,15-24
2,3,3,18,Male,Cairo,0.95,0,WE,Mobile Data,NaN,0.0,NaN,0,0,2023,No internet coverage,15-24
3,4,4,21,Male,Delta,0.60,1,WE,Mobile Data,WE Mobile 20GB,5.3,Social Media,120,10,2021,IS_Internet_User,15-24
4,5,5,40,Female,Cairo,0.95,1,WE,Mobile Data,WE Mobile 40GB,3.8,Work,200,20,2016,IS_Internet_User,35-44

In [31]:
df_Data.to_csv("Egypt_Internet_Usage.csv")

In [32]:
df_Data['Internet_Speed_In_Region'] = df_Data['region_name'].map({"Alexandria":13.7, "Cairo": 15.8, "Upper Egypt" : 12, "Giza" : 17.1 , "Delta": 14})

In [33]:
df_Data[['region_name', 'Internet_Speed_In_Region']].drop_duplicates()

   region_name  Internet_Speed_In_Region
0         Giza                      17.1
1        Cairo                      15.8
3        Delta                      14.0
6  Upper Egypt                      12.0
8   Alexandria                      13.7

In [34]:
# 1. How has internet usage penetration changed over the years?
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
users = Internet_Users.groupby("year")['is_internet_user'].count().reset_index()
total = df_Data.groupby("year")['is_internet_user'].count().reset_index()
users['is_internet_user'] / total['is_internet_user']

0    0.821488
1    0.842022
2    0.817734
3    0.821818
4    0.824348
5    0.836177
6    0.794069
7    0.824561
8    0.828666
9    0.830283
Name: is_internet_user, dtype: float64

In [35]:
# 2. Which year experienced the highest growth in internet adoption?
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
users = Internet_Users.groupby("year")['is_internet_user'].count().reset_index(name="Count")
users['growth'] = None
for i in range(len(users)):
  if i > 0:
    users.loc[i , 'growth'] = users['Count'][i] - users['Count'][i-1]

users.loc[0, 'growth'] = -1
users.loc[users['growth'].max() == users['growth'], 'year']

1    2016
Name: year, dtype: int64

In [36]:
# 3.Has average daily internet usage increased over time?
Average_usage = df_Data.groupby('year')['daily_hours'].mean().reset_index()
Average_usage['increase Rate'] = None
for i in range(len(Average_usage)):
    if i > 0:
      Average_usage.loc[i , 'increase Rate'] = Average_usage['daily_hours'][i] - Average_usage['daily_hours'][i-1]
Average_usage

   year  daily_hours increase Rate
0  2015     3.852727          None
1  2016     3.944866      0.092138
2  2017     3.865846      -0.07902
3  2018     3.947273      0.081427
4  2019     3.875130     -0.072142
5  2020     3.929522      0.054392
6  2021     3.770840     -0.158682
7  2022     3.745295     -0.025545
8  2023     3.874465       0.12917
9  2024     3.948586      0.074121

In [37]:
# 4. Is internet usage growth slowing or accelerating in recent years?
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
users = Internet_Users.groupby("year")['is_internet_user'].count().reset_index()
total = df_Data.groupby("year")['is_internet_user'].count().reset_index(name ='Total Internet users')
rate = users.merge(total, on = 'year' ,how='left')
rate['growth'] = rate['is_internet_user'] / rate['Total Internet users']
rate['increase Rate'] = rate['growth'].diff()
rate

   year  is_internet_user  Total Internet users    growth  increase Rate
0  2015               497                   605  0.821488            NaN
1  2016               533                   633  0.842022       0.020535
2  2017               498                   609  0.817734      -0.024288
3  2018               452                   550  0.821818       0.004084
4  2019               474                   575  0.824348       0.002530
5  2020               490                   586  0.836177       0.011830
6  2021               482                   607  0.794069      -0.042108
7  2022               517                   627  0.824561       0.030492
8  2023               503                   607  0.828666       0.004104
9  2024               499                   601  0.830283       0.001617

In [38]:
#5. How does mobile vs fixed broadband adoption change over time?
Internet_Users_Only = df_Data[df_Data['is_internet_user']==1]
adoption = Internet_Users_Only.groupby(['connection_type', 'year'])['is_internet_user'].count().reset_index(name = 'users')
adoption['Rate'] = adoption.groupby('connection_type')['users'].diff()
adoption

    connection_type  year  users  Rate
0   Fixed Broadband  2015    128   NaN
1   Fixed Broadband  2016    162  34.0
2   Fixed Broadband  2017    148 -14.0
3   Fixed Broadband  2018    130 -18.0
4   Fixed Broadband  2019    121  -9.0
5   Fixed Broadband  2020    140  19.0
6   Fixed Broadband  2021    117 -23.0
7   Fixed Broadband  2022    133  16.0
8   Fixed Broadband  2023    116 -17.0
9   Fixed Broadband  2024    135  19.0
10      Mobile Data  2015    369   NaN
11      Mobile Data  2016    371   2.0
12      Mobile Data  2017    350 -21.0
13      Mobile Data  2018    322 -28.0
14      Mobile Data  2019    353  31.0
15      Mobile Data  2020    350  -3.0
16      Mobile Data  2021    365  15.0
17      Mobile Data  2022    384  19.0
18      Mobile Data  2023    387   3.0
19      Mobile Data  2024    364 -23.0

In [39]:
# 6. How does internet usage intensity vary by age group?
df_Data.groupby("Age_Group")['daily_hours'].mean().sort_index(ascending=True).reset_index(name= "Average Using")

  Age_Group  Average Using
0     15-24       5.204266
1     25-34       4.489864
2     35-44       3.761512
3     45-54       3.101104
4       55+       2.061506

In [40]:
# 7.Which age group has the highest internet adoption rate?
Internet_Users_Only = df_Data[df_Data['is_internet_user']==1]
users = Internet_Users_Only.groupby('Age_Group')['is_internet_user'].count().reset_index(name = 'users')
total = df_Data.groupby("Age_Group")['is_internet_user'].count().reset_index(name ='Total Population')
adoption = users.merge(total, on='Age_Group')
adoption['Rate'] = adoption['users'] / adoption['Total Population']
adoption

  Age_Group  users  Total Population      Rate
0     15-24   1107              1336  0.828593
1     25-34   1200              1470  0.816327
2     35-44    961              1164  0.825601
3     45-54    904              1087  0.831647
4       55+    773               943  0.819724

In [41]:
#8. Are younger users more likely to use mobile data than fixed broadband?
younger_users = df_Data[(df_Data['Age_Group'] =='15-24') & (df_Data['is_internet_user'] == 1)]
younger_users.groupby('connection_type')['is_internet_user'].count().sort_values(ascending=False)

connection_type
Mobile Data        803
Fixed Broadband    304
Name: is_internet_user, dtype: int64

In [42]:
# 9. Which age groups are most likely to be non-internet users?
Non_Internet_Users_Only = df_Data[df_Data['is_internet_user']==0]
users = Non_Internet_Users_Only.groupby('Age_Group')['is_internet_user'].count().reset_index(name = 'users').sort_values(by = 'users', ascending=False)
users

  Age_Group  users
1     25-34    270
0     15-24    229
2     35-44    203
3     45-54    183
4       55+    170

In [43]:
# 10. Which regions have the highest internet penetration? DESCENDING
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
total = df_Data.groupby('region_name')['is_internet_user'].count().reset_index(name ='Population')
users = Internet_Users.groupby("region_name")['is_internet_user'].count().reset_index(name ='Internet_users')
penetration = total.merge(users , on = 'region_name' )
penetration['penetration_Rate'] = penetration['Internet_users'] / penetration['Population']
penetration.sort_values(by = 'penetration_Rate', ascending=False)

   region_name  Population  Internet_users  penetration_Rate
3         Giza        1096             916          0.835766
4  Upper Egypt        1161             966          0.832041
1        Cairo        1316            1094          0.831307
2        Delta        1733            1415          0.816503
0   Alexandria         694             554          0.798271

In [44]:
# 10. Which regions have the lowest internet penetration? ASCENDING
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
total = df_Data.groupby('region_name')['is_internet_user'].count().reset_index(name ='Population')
users = Internet_Users.groupby("region_name")['is_internet_user'].count().reset_index(name ='Internet_users')
penetration = total.merge(users , on = 'region_name' )
penetration['penetration_Rate'] = penetration['Internet_users'] / penetration['Population']
penetration.sort_values(by = 'penetration_Rate', ascending=True)

   region_name  Population  Internet_users  penetration_Rate
0   Alexandria         694             554          0.798271
2        Delta        1733            1415          0.816503
1        Cairo        1316            1094          0.831307
4  Upper Egypt        1161             966          0.832041
3         Giza        1096             916          0.835766

In [45]:
#11. Is urbanization level correlated with internet usage?
internet_users = df_Data[df_Data['is_internet_user'] == 1]
internet_users['urban_level'].corr(other=internet_users['daily_hours'])

np.float64(0.003222165369539195)

In [46]:
#12. Do urban regions spend more on internet services than rural ones?
Regions = df_Data.groupby('region_name')['monthly_cost_egp'].mean().reset_index(name ='total_Money_Spent').sort_values(by='total_Money_Spent', ascending= False )
Regions

   region_name  total_Money_Spent
1        Cairo         238.525836
3         Giza         237.883212
0   Alexandria         236.383285
4  Upper Egypt         235.486649
2        Delta         228.170802

In [47]:
#13. Which regions have the highest concentration of non-users?
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
total = df_Data.groupby('region_name')['is_internet_user'].count().reset_index(name ='Population')
users = Internet_Users.groupby("region_name")['is_internet_user'].count().reset_index(name ='Internet_users')
penetration = total.merge(users , on = 'region_name' )
penetration['penetration_Rate'] = penetration['Internet_users'] / penetration['Population']
penetration.sort_values(by = 'penetration_Rate', ascending=True)

   region_name  Population  Internet_users  penetration_Rate
0   Alexandria         694             554          0.798271
2        Delta        1733            1415          0.816503
1        Cairo        1316            1094          0.831307
4  Upper Egypt        1161             966          0.832041
3         Giza        1096             916          0.835766

In [48]:
#14. What is the market share of each ISP?
with_ISP_Only = df_Data[(df_Data['isp'] != 'No is Sim Owner')]
total = with_ISP_Only.shape[0]
ISP = with_ISP_Only.groupby('isp')['user_id'].count().reset_index(name='users')
ISP['Market_Share'] = ISP['users'] / total
ISP

        isp  users  Market_Share
0  Etisalat    903      0.150500
1    Orange   1043      0.173833
2  Vodafone   1352      0.225333
3        WE   2702      0.450333

In [49]:
#15. Does ISP preference differ by region?
Internet_Users = df_Data[df_Data['is_internet_user'] == 1]
users = Internet_Users.groupby(["region_name", 'isp'])['user_id'].count().reset_index(name ='total_subscriptors')
users

    region_name       isp  total_subscriptors
0    Alexandria  Etisalat                  85
1    Alexandria    Orange                  90
2    Alexandria  Vodafone                 126
3    Alexandria        WE                 253
4         Cairo  Etisalat                 171
5         Cairo    Orange                 177
6         Cairo  Vodafone                 243
7         Cairo        WE                 503
8         Delta  Etisalat                 203
9         Delta    Orange                 256
10        Delta  Vodafone                 337
11        Delta        WE                 619
12         Giza  Etisalat                 136
13         Giza    Orange                 155
14         Giza  Vodafone                 204
15         Giza        WE                 421
16  Upper Egypt  Etisalat                 146
17  Upper Egypt    Orange                 170
18  Upper Egypt  Vodafone                 223
19  Upper Egypt        WE                 427

In [50]:
#16. Which ISP has the highest average revenue per user (ARPU)?
ISP = df_Data.groupby('isp')['monthly_cost_egp'].mean().reset_index(name ='total_Money_Spent').sort_values(by='total_Money_Spent', ascending= False )
ISP

        isp  total_Money_Spent
2  Vodafone         263.624260
1    Orange         241.150527
0  Etisalat         237.696567
3        WE         216.472983

In [51]:
#17.Are certain ISPs more popular among mobile or fixed broadband users?
ISP = df_Data.groupby(['isp', 'connection_type'])['user_id'].count().reset_index(name ='total_Users').sort_values(by='total_Users', ascending= False )
ISP

        isp  connection_type  total_Users
7        WE      Mobile Data         1966
5  Vodafone      Mobile Data          971
3    Orange      Mobile Data          741
6        WE  Fixed Broadband          736
1  Etisalat      Mobile Data          672
4  Vodafone  Fixed Broadband          381
2    Orange  Fixed Broadband          302
0  Etisalat  Fixed Broadband          231

In [52]:
#18.Does higher internet cost correspond to higher usage or speed?
df_Data['monthly_cost_egp'].corr(df_Data['daily_hours'])

np.float64(0.5626049695158907)

In [53]:
#19. What are the main reasons for not using the internet, and who are the non-users?
Non_users = df_Data[df_Data['Reason_Not_Using_Internet'] !='IS_Internet_User']
Non_users.groupby('Reason_Not_Using_Internet')['user_id'].count().reset_index(name='Number of non_user for this reason').sort_values(by = 'Number of non_user for this reason', ascending=False)

  Reason_Not_Using_Internet  Number of non_user for this reason
0      Cannot afford device                                 322
2      No internet coverage                                 246
1      Low digital literacy                                 198
3         No perceived need                                 176
4       Physical disability                                 113

In [54]:
#20. Which regions or age groups represent the highest potential for future internet growth?
Non_users = df_Data[df_Data['is_internet_user'] == 0]
Users = df_Data[df_Data['is_internet_user'] == 1]
Highest_Reasons_With_Age_users= Users.groupby(['region_name', 'Age_Group'])['user_id'].count().reset_index(name='user_count').sort_values(by = 'user_count', ascending=False)
Highest_Reasons_With_Age_Non_users= Non_users.groupby(['region_name', 'Age_Group'])['user_id'].count().reset_index(name='Non_users_count').sort_values(by = 'Non_users_count', ascending=False)
Potential_Growth = Highest_Reasons_With_Age_users.merge(Highest_Reasons_With_Age_Non_users , how='outer' , on=['region_name', 'Age_Group'])
Potential_Growth['Growth_Rate'] = Potential_Growth['Non_users_count'] / (Potential_Growth['user_count'] + Potential_Growth['Non_users_count'])
Potential_Growth

    region_name Age_Group  user_count  Non_users_count  Growth_Rate
0    Alexandria     15-24         123               30     0.196078
1    Alexandria     25-34         124               37     0.229814
2    Alexandria     35-44         106               30     0.220588
3    Alexandria     45-54         115               23     0.166667
4    Alexandria       55+          86               20     0.188679
5         Cairo     15-24         258               53     0.170418
6         Cairo     25-34         263               53     0.167722
7         Cairo     35-44         209               47     0.183594
8         Cairo     45-54         192               39     0.168831
9         Cairo       55+         172               30     0.148515
10        Delta     15-24         306               54     0.150000
11        Delta     25-34         374               93     0.199143
12        Delta     35-44         256               59     0.187302
13        Delta     45-54         242               57     0.190635
14        Delta       55+         237               55     0.188356
15         Giza     15-24         218               48     0.180451
16         Giza     25-34         203               34     0.143460
17         Giza     35-44         184               34     0.155963
18         Giza     45-54         177               36     0.169014
19         Giza       55+         134               28     0.172840
20  Upper Egypt     15-24         202               44     0.178862
21  Upper Egypt     25-34         236               53     0.183391
22  Upper Egypt     35-44         206               33     0.138075
23  Upper Egypt     45-54         178               28     0.135922
24  Upper Egypt       55+         144               37     0.204420

In [55]:
print(f"Features Number is: {len(df_Data.columns.to_list())}")

Features Number is: 18